console.log('hello world')

//변수
/**
변수: let, var 
상수: const
가수:singer
 */

const irum='Seo ga eun';
console.log('name',irum);


//    irum='park!!';    //상수라 오류남
/* console.log('new name', irum);

var a;
console.log('a',a); //선언 안했는데 작동함
a=10;
console.log('a',a);
/* a=20
console.log('new-a',a); */
//작동함
/*
console.log('-------------------------');

var b;
console.log('b',b);
 */

/* console.log('-------------------------');

let su;
su=10;
console.log(su); */


console.log('-------------------------');

let a=10;
let b='aaa';
let c=10.2;
let d=10==10;
let e;
let f=null;

console.log(a,typeof(a));
console.log(b, typeof(b));
console.log(c, typeof(c));
console.log(d, typeof(d));
console.log(e, typeof(e));
console.log(f, typeof(f));
console.log(10/0, '10/0');
console.log(-10/0,'-10/0');
console.log('aa'/10,'aa/10');
